# Generated by Django 4.1.7 on 2023-03-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contestants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("age", models.IntegerField(default=20, null=True)),
                ("hometown", models.CharField(default="", max_length=100, null=True)),
                ("cycle", models.IntegerField(default=1, null=True)),
                ("elim", models.CharField(default="14th", max_length=5, null=True)),
            ],
        ),
    ]
